### ISSUE TITLE
Realizar el "home" de la pagina 

### ISSUE THREAD

**Issue by franlesk** [franlesk/Proyectogfinalprog1#13]
-Se debera realizar un "include" de la navbar.php importando al archivo tambien sus "estilos".
-El "home" debera seguir los "estilos" de la ventana de "categorias".
-Debera traer utilizando "rand" 1 producto de cada categoria de la base de datos.
-Los productos se deberan mostrar en "grid" al igual que la ventana "categorias".

**Comment by briantabo** [comment]
Se realizo el home de la pagina, incluyendo la navbar.php y importando sus estilos. Se realizo el CSS del mismo, también se realizo el "rand" para traer un producto de cada categoría de la base de datos.
